# Generated by Django 2.1 on 2018-11-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keghistory',
            old_name='Keg',
            new_name='keg',
        ),
        migrations.AlterField(
            model_name='keghistory',
            name='amountSold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='keghistory',
            name='closingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keghistory',
            name='quantitySold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
