# Generated by Django 2.1 on 2018-11-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20181123_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keg',
            options={'permissions': (('open_keg', 'Peut percuter les fûts'), ('close_keg', 'Peut fermer les fûts'))},
        ),
        migrations.AddField(
            model_name='product',
            name='adherentRequired',
            field=models.BooleanField(default=True),
        ),
    ]
