# Generated by Django 2.1 on 2018-12-23 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_historicalpinte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinte',
            name='current_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pintes_owned_currently', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pinte',
            name='previous_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pintes_owned_previously', to=settings.AUTH_USER_MODEL),
        ),
    ]
