# Generated by Django 2.1 on 2018-11-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20181126_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmenuhistory',
            old_name='PaymentMethod',
            new_name='paymentMethod',
        ),
        migrations.RenameField(
            model_name='menuhistory',
            old_name='PaymentMethod',
            new_name='paymentMethod',
        ),
    ]
