# Generated by Django 2.1 on 2018-11-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20181127_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumptionhistory',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='historicalconsumptionhistory',
            name='menu',
        ),
    ]
