# Generated by Django 2.1 on 2019-05-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20190503_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='draft_category',
            field=models.IntegerField(choices=[(0, 'Pas une bière pression'), (1, 'Pinte'), (2, 'Demi'), (3, 'Galopin')], default=0, verbose_name='Type de pression'),
        ),
        migrations.AddField(
            model_name='product',
            name='draft_category',
            field=models.IntegerField(choices=[(0, 'Pas une bière pression'), (1, 'Pinte'), (2, 'Demi'), (3, 'Galopin')], default=0, verbose_name='Type de pression'),
        ),
    ]
