# Generated by Django 2.1 on 2018-12-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20181130_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstocking',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Stocking',
        ),
        migrations.AlterModelOptions(
            name='consumption',
            options={'verbose_name': 'Consommation totale'},
        ),
        migrations.AlterModelOptions(
            name='consumptionhistory',
            options={'verbose_name': 'Consommation'},
        ),
        migrations.AlterModelOptions(
            name='historicalconsumption',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Consommation totale'},
        ),
        migrations.AlterModelOptions(
            name='historicalconsumptionhistory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Consommation'},
        ),
        migrations.AlterModelOptions(
            name='historicalkeg',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Fût'},
        ),
        migrations.AlterModelOptions(
            name='historicalkeghistory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Historique de fût'},
        ),
        migrations.AlterModelOptions(
            name='historicalmenuhistory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Historique de menu'},
        ),
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Produit'},
        ),
        migrations.AlterModelOptions(
            name='historicalrefund',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Remboursement'},
        ),
        migrations.AlterModelOptions(
            name='historicalreload',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Rechargement'},
        ),
        migrations.AlterModelOptions(
            name='keg',
            options={'permissions': (('open_keg', 'Peut percuter les fûts'), ('close_keg', 'Peut fermer les fûts')), 'verbose_name': 'Fût'},
        ),
        migrations.AlterModelOptions(
            name='keghistory',
            options={'verbose_name': 'Historique de fût'},
        ),
        migrations.AlterModelOptions(
            name='menuhistory',
            options={'verbose_name': 'Historique de menu'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': 'Remboursement'},
        ),
        migrations.AlterModelOptions(
            name='reload',
            options={'verbose_name': 'Rechargement'},
        ),
        migrations.DeleteModel(
            name='HistoricalStocking',
        ),
    ]
