# Generated by Django 2.1 on 2019-08-27 19:19

from django.db import migrations, models

def update(apps, schema_editor):
    Product = apps.get_model('gestion', 'Product')
    for product in Product.objects.all():
        product.stock = product.stockBar
        product.save()

def reverse(apps, schema_editor):
    Product = apps.get_model('gestion', 'Product')
    for product in Product.objects.all():
        product.stockBar = product.stock
        product.save()



class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20190623_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.RunPython(update, reverse),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='stockBar',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='stockHold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stockBar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stockHold',
        ),
    ]
