# Generated by Django 2.1 on 2019-08-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_auto_20190827_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='use_stocks',
            field=models.BooleanField(default=True, verbose_name='Utiliser les stocks ?'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_stocks',
            field=models.BooleanField(default=True, verbose_name='Utiliser les stocks ?'),
        ),
    ]
