# Generated by Django 2.1 on 2019-02-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
