# Generated by Django 2.1 on 2018-11-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181009_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotisationhistory',
            options={'permissions': (('validate_consumptionhistory', 'Peut (in)valider les cotisations'),)},
        ),
    ]
