# Generated by Django 2.1 on 2019-02-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190218_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='date_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_verified',
        ),
    ]
