# Generated by Django 2.1 on 2019-02-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190219_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotisationhistory',
            options={'verbose_name': 'Historique cotisation'},
        ),
        migrations.RemoveField(
            model_name='cotisationhistory',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='historicalcotisationhistory',
            name='valid',
        ),
    ]
