# Generated by Django 2.1 on 2018-12-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalcotisationhistory_historicalprofile_historicalschool_historicalwhitelisthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotisationhistory',
            options={'permissions': (('validate_cotisationhistory', 'Peut (in)valider les cotisations'),), 'verbose_name': 'Historique cotisation'},
        ),
        migrations.AlterModelOptions(
            name='historicalcotisationhistory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Historique cotisation'},
        ),
        migrations.AlterModelOptions(
            name='historicalprofile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Profil'},
        ),
        migrations.AlterModelOptions(
            name='historicalschool',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical École'},
        ),
        migrations.AlterModelOptions(
            name='historicalwhitelisthistory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Historique accès gracieux'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'École'},
        ),
        migrations.AlterModelOptions(
            name='whitelisthistory',
            options={'verbose_name': 'Historique accès gracieux'},
        ),
    ]
