# Generated by Django 2.1 on 2019-02-27 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190226_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelisthistory',
            options={'verbose_name': 'Historique accès gracieux', 'verbose_name_plural': 'Historique accès gracieux'},
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='cotisationEnd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de cotisation'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Crédit'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Débit'),
        ),
        migrations.AlterField(
            model_name='historicalwhitelisthistory',
            name='endDate',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='historicalwhitelisthistory',
            name='paymentDate',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cotisationEnd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de cotisation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Crédit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Débit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.School', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='whitelisthistory',
            name='endDate',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='whitelisthistory',
            name='paymentDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='whitelisthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
