# Generated by Django 2.1 on 2018-12-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181202_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
