# Generated by Django 2.1 on 2019-06-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190623_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisationhistory',
            name='amount_ptm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Montant pour le club Phœnix Technopôle Metz'),
        ),
        migrations.AlterField(
            model_name='historicalcotisationhistory',
            name='amount_ptm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Montant pour le club Phœnix Technopôle Metz'),
        ),
    ]
