# Generated by Django 2.1 on 2019-09-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190627_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_generate_invoices', 'Can generate invocies'), ('can_change_user_perm', 'Can change user groups')), 'verbose_name': 'Profil'},
        ),
    ]
