# Generated by Django 2.1 on 2018-08-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('active_message', models.TextField(blank=True)),
                ('global_message', models.TextField(blank=True)),
                ('president', models.CharField(blank=True, max_length=255)),
                ('vice_president', models.CharField(blank=True, max_length=255)),
                ('treasurer', models.CharField(blank=True, max_length=255)),
                ('secretary', models.CharField(blank=True, max_length=255)),
                ('brewer', models.CharField(blank=True, max_length=255)),
                ('grocer', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
