# Generated by Django 2.1 on 2018-12-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpreferences',
            name='use_pinte_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgeneralpreferences',
            name='use_pinte_monitoring',
            field=models.BooleanField(default=False),
        ),
    ]
