# Generated by Django 2.1 on 2018-10-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_usable_in_reload',
            field=models.BooleanField(default=True, verbose_name='Rechargements ?'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='affect_balance',
            field=models.BooleanField(default=False, verbose_name='Affecte le solde'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_usable_in_cotisation',
            field=models.BooleanField(default=True, verbose_name='Cotisations ?'),
        ),
    ]
