# Generated by Django 2.1 on 2018-12-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181221_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpreferences',
            name='lost_pintes_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalgeneralpreferences',
            name='lost_pintes_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
