# Generated by Django 2.1 on 2018-11-26 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_historicalcotisation_historicalgeneralpreferences_historicalpaymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='historicalcotisation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
    ]
