# Generated by Django 2.1 on 2019-01-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_auto_20181223_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='icon',
            field=models.CharField(blank=True, max_length=255, verbose_name='Icône'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='icon',
            field=models.CharField(blank=True, max_length=255, verbose_name='Icône'),
        ),
    ]
