# Generated by Django 2.1 on 2019-01-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_auto_20190106_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpreferences',
            name='floating_buttons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgeneralpreferences',
            name='floating_buttons',
            field=models.BooleanField(default=False),
        ),
    ]
