# Generated by Django 2.1 on 2019-01-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_auto_20190106_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpreferences',
            name='home_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalgeneralpreferences',
            name='home_text',
            field=models.TextField(blank=True),
        ),
    ]
