# Generated by Django 2.1 on 2019-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0007_auto_20190120_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpreferences',
            name='menu',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='generalpreferences',
            name='rules',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='generalpreferences',
            name='statutes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='historicalgeneralpreferences',
            name='menu',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalgeneralpreferences',
            name='rules',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalgeneralpreferences',
            name='statutes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
