# Generated by Django 2.1 on 2019-02-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0008_auto_20190218_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalpreferences',
            options={'verbose_name': 'Préférences générales', 'verbose_name_plural': 'Préférences générales'},
        ),
        migrations.AlterModelOptions(
            name='historicalgeneralpreferences',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Préférences générales'},
        ),
        migrations.AlterModelOptions(
            name='historicalpaymentmethod',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Moyen de paiement'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Moyen de paiement', 'verbose_name_plural': 'Moyens de paiement'},
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='active_message',
            field=models.TextField(blank=True, verbose_name='Message non actif'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='automatic_logout_time',
            field=models.PositiveIntegerField(null=True, verbose_name='Temps de déconnexion automatique'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='brewer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maître Brasseur'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='floating_buttons',
            field=models.BooleanField(default=False, verbose_name='Boutons flottants'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='global_message',
            field=models.TextField(blank=True, verbose_name='Message global'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='grocer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Épic Épicier'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='home_text',
            field=models.TextField(blank=True, verbose_name="Message d'accueil"),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Site actif'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='lost_pintes_allowed',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de pintes perdus admises'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='menu',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='president',
            field=models.CharField(blank=True, max_length=255, verbose_name='Président'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='rules',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Règlement intérieur'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='secretary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Secrétaire'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='statutes',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Statuts'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='treasurer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Trésorier'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='use_pinte_monitoring',
            field=models.BooleanField(default=False, verbose_name='Suivi de pintes'),
        ),
        migrations.AlterField(
            model_name='generalpreferences',
            name='vice_president',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vice Président'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='active_message',
            field=models.TextField(blank=True, verbose_name='Message non actif'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='automatic_logout_time',
            field=models.PositiveIntegerField(null=True, verbose_name='Temps de déconnexion automatique'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='brewer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maître Brasseur'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='floating_buttons',
            field=models.BooleanField(default=False, verbose_name='Boutons flottants'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='global_message',
            field=models.TextField(blank=True, verbose_name='Message global'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='grocer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Épic Épicier'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='home_text',
            field=models.TextField(blank=True, verbose_name="Message d'accueil"),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Site actif'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='lost_pintes_allowed',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de pintes perdus admises'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='menu',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='president',
            field=models.CharField(blank=True, max_length=255, verbose_name='Président'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='rules',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Règlement intérieur'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='secretary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Secrétaire'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='statutes',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Statuts'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='treasurer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Trésorier'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='use_pinte_monitoring',
            field=models.BooleanField(default=False, verbose_name='Suivi de pintes'),
        ),
        migrations.AlterField(
            model_name='historicalgeneralpreferences',
            name='vice_president',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vice Président'),
        ),
    ]
