# Generated by Django 2.1 on 2019-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0009_auto_20190227_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpreferences',
            name='alchohol_charter',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Charte alcool'),
        ),
        migrations.AddField(
            model_name='historicalgeneralpreferences',
            name='alchohol_charter',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Charte alcool'),
        ),
    ]
