# Generated by Django 2.1 on 2019-04-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0010_auto_20190428_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalpreferences',
            old_name='alchohol_charter',
            new_name='alcohol_charter',
        ),
        migrations.RenameField(
            model_name='historicalgeneralpreferences',
            old_name='alchohol_charter',
            new_name='alcohol_charter',
        ),
    ]
