# Generated by Django 2.1 on 2019-04-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0011_auto_20190428_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpreferences',
            name='brewer',
        ),
        migrations.RemoveField(
            model_name='generalpreferences',
            name='grocer',
        ),
        migrations.RemoveField(
            model_name='generalpreferences',
            name='vice_president',
        ),
        migrations.RemoveField(
            model_name='historicalgeneralpreferences',
            name='brewer',
        ),
        migrations.RemoveField(
            model_name='historicalgeneralpreferences',
            name='grocer',
        ),
        migrations.RemoveField(
            model_name='historicalgeneralpreferences',
            name='vice_president',
        ),
        migrations.AddField(
            model_name='generalpreferences',
            name='phoenixTM_responsible',
            field=models.CharField(blank=True, max_length=255, verbose_name='Responsable Phœnix Technopôle Metz'),
        ),
        migrations.AddField(
            model_name='historicalgeneralpreferences',
            name='phoenixTM_responsible',
            field=models.CharField(blank=True, max_length=255, verbose_name='Responsable Phœnix Technopôle Metz'),
        ),
    ]
