# Generated by Django 2.1 on 2019-06-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0012_auto_20190428_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='amount_ptm',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Montant pour le club Phœnix Technopôle Metz'),
        ),
        migrations.AddField(
            model_name='historicalcotisation',
            name='amount_ptm',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Montant pour le club Phœnix Technopôle Metz'),
        ),
    ]
