# Generated by Django 2.1 on 2019-06-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0013_auto_20190622_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotisation',
            options={'permissions': (('can_divide', 'Can divide money for cotisation'),)},
        ),
    ]
