# Generated by Django 2.1 on 2019-06-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0016_priceprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceprofile',
            name='alpha',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Étendue'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='b',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Marge variable'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='c',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Paramètre de forme'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='priceprofile',
            name='use_for_draft',
            field=models.BooleanField(default=False, verbose_name='Utiliser pour les pressions ?'),
        ),
    ]
